# Generated by Django 4.2.17 on 2025-01-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userpreferences_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='city',
            field=models.CharField(max_length=40),
        ),
    ]
