# Generated by Django 4.2.17 on 2025-01-18 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_apartmentuserlike'),
        ('users', '0003_alter_userpreferences_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='apartments.city'),
        ),
    ]
