# Generated by Django 4.2.17 on 2025-01-03 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_logininfo_userdetails_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logininfo",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="phone_number",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("area", models.CharField(max_length=200)),
                ("min_price", models.IntegerField()),
                ("max_price", models.IntegerField()),
                ("move_in_date", models.DateField()),
                ("number_of_roommates", models.IntegerField()),
                (
                    "login_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_preferences",
                        to="users.logininfo",
                    ),
                ),
            ],
        ),
    ]
