# Generated by Django 4.2.17 on 2025-01-12 18:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0002_populate_features"),
        ("users", "0005_alter_logininfo_email_alter_userdetails_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdetails",
            name="address",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="area",
        ),
        migrations.AddField(
            model_name="userdetails",
            name="about_me",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="userdetails",
            name="preferred_city",
            field=models.CharField(default="tel-aviv", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="city",
            field=models.CharField(default="tel-aviv", max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="occupation",
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name="UserPreferencesFeatures",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_users",
                        to="apartments.feature",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_preference_features",
                        to="users.userpreferences",
                    ),
                ),
            ],
        ),
    ]
