# Generated by Django 5.1.4 on 2025-01-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_userdetails_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="photo",
            field=models.ImageField(null=True, upload_to="user_photo/"),
        ),
    ]
