# Generated by Django 4.2.17 on 2025-01-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userdetails_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='photo',
            field=models.ImageField(null=True, upload_to='users/photos/'),
        ),
    ]
