# Generated by Django 4.2.17 on 2025-01-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userdetails_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='userpreferencesfeatures',
            old_name='user',
            new_name='user_preferences',
        ),
    ]
