# Generated by Django 4.2.17 on 2025-03-31 21:28

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_alter_userpreferences_user'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL: Add user_id column, set it to NULL initially
            """
            ALTER TABLE users_userpreferences 
            ADD COLUMN user_id integer NULL REFERENCES auth_user(id) ON DELETE CASCADE;
            """,
            # Reverse SQL: Remove user_id column
            """
            ALTER TABLE users_userpreferences 
            DROP COLUMN user_id;
            """
        ),
        migrations.RunSQL(
            # Forward SQL: Remove login_info_id column
            """
            ALTER TABLE users_userpreferences 
            DROP COLUMN login_info_id;
            """,
            # Reverse SQL: Add login_info_id column back
            """
            ALTER TABLE users_userpreferences 
            ADD COLUMN login_info_id uuid NULL;
            """
        ),
    ]
