# Generated by Django 4.2.17 on 2025-04-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_questionnaire_alter_userpreferences_city_and_more'),
        ('users', '0009_auto_20250331_2128'),
    ]

    operations = [
    ]
