# Generated by Django 4.2.17 on 2025-04-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_question_questionnairetemplate_userresponse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnairetemplate',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='questionnairetemplate',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
