# Generated by Django 4.2.17 on 2025-04-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_userdetails_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.FloatField(default=1.0, help_text='Weight factor for this question in compatibility calculations'),
        ),
    ]
