# Generated by Django 4.2.17 on 2025-04-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_question_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_yad2',
            field=models.BooleanField(default=False),
        ),
    ]
