# Generated by Django 4.2.17 on 2025-04-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userdetails_is_yad2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='area',
            field=models.CharField(blank=True, help_text='Preferred neighborhood or area', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='max_floor',
            field=models.IntegerField(blank=True, help_text='Maximum floor preference (optional)', null=True),
        ),
    ]
