# Generated by Django 4.2.17 on 2025-04-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_userpreferences_area_userpreferences_max_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='max_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='min_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='number_of_roommates',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
