# Generated by Django 4.2.17 on 2025-05-17 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_useruserlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_jti', models.CharField(db_index=True, max_length=255, unique=True)),
                ('user_id', models.IntegerField(null=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'blacklisted_tokens',
            },
        ),
    ]
