# Generated by Django 4.2.17 on 2025-01-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_populate_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentphoto',
            name='photo',
            field=models.ImageField(upload_to='apartments/photos'),
        ),
    ]
