# Generated by Django 5.1.4 on 2025-01-14 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0003_alter_apartmentphoto_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("hebrew_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="apartment",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="street",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apartments",
                to="apartments.city",
            ),
        ),
    ]
