# Generated by Django 5.1.4 on 2025-01-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0005_apartment_created_at_apartment_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="house_number",
            field=models.IntegerField(),
        ),
    ]
