# Generated by Django 4.2.17 on 2025-01-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0006_alter_apartment_house_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
