# Generated by Django 4.2.17 on 2025-04-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_apartment_user'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DELETE FROM apartments_apartmentphoto;
            UPDATE users_userdetails SET photo = NULL;
            """,
            reverse_sql="""
            -- No reverse operation needed
            """
        ),
    ]
