# Generated by Django 4.2.17 on 2025-04-04 13:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0010_delete_existing_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentphoto',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
