# Generated by Django 4.2.17 on 2025-04-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0012_apartment_area_apartment_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='house_number',
        ),
        migrations.AddField(
            model_name='apartment',
            name='is_yad2',
            field=models.BooleanField(default=False),
        ),
    ]
