# Generated by Django 4.2.17 on 2025-06-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0017_update_apartment_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
