# Generated by Django 4.2.17 on 2025-06-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0018_alter_apartment_total_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='apartmentfeature',
            constraint=models.UniqueConstraint(fields=('apartment', 'feature'), name='unique_apartment_feature'),
        ),
        migrations.AddConstraint(
            model_name='apartmentuserlike',
            constraint=models.UniqueConstraint(fields=('apartment', 'user'), name='unique_apartment_user_like'),
        ),
    ]
